services:
  ylem_kafka_trigger:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ylem_kafka_trigger
    #networks:
    #  - ylem_network
    volumes:
      - .:/go/src/kafkatrigger
    working_dir: /go/src/kafkatrigger
    stdin_open: true
    tty: true

# uncomment if you want to include the container to the existing network
#networks:
#  default:
#    name: ylem_network
#    external: true
